### PR TITLE
Minor fixes to support running on (old) Android environments.

### LINKED ISSUE #108: Android support
Just checking if there would be interest in making hoplite work on Android?

I could probably do it as part of my current project, since I would like to use hoplite, but just wanted to check before I start on it.

From a brief look, I've found the following issues that need to be resolved (there may be more, of course):

- FileSource needs to support a third type of data. The reason is that only very recent Android SDKs have support for Paths and most Android data will be in the assets store anyway. I would propose a kind of "GenericFileSource" with a constructor that takes an InputStream and extension-string, so it could be used for "anything". Alternatively, perhaps FileSource could be made open for extensions, so users can add any kind they want?
- EnvVarProcessor has a regexp that Android thinks is invalid. I'm expecting this will just be a matter of changing it slightly.
- javax.security does not exist in Android. I would propose to move those Decoders to a separate lib, similar to how Arrow is handled

### PR DESCRIPTION
**Pull request by ttorjan**
Fixes #108 

  * Android has a custom Regex parser which is not compliant. It needs the closing brace to be escaped as well for variable substitution preprocessors. Shouldn't hurt other platforms, though, only emit warnings about unnecessary escaping.
  * "Unsealed" FileSource so it can be extended externally (required for Android to be able to read from assets).
  * Added "FileIoSource" FileSource implementation that does not use APIs only available in Android Oreo (Files and Path).
  * Moved Decoders for javax APIs to new module that can be excluded for platforms that don't have javax (guess which one).

### CODE REVIEW

File: hoplite-core/src/main/kotlin/com/sksamuel/hoplite/FileSource.kt [hunk 1]
```diff
@@ -4,11 +4,13 @@ import com.sksamuel.hoplite.fp.Try
...
 import com.sksamuel.hoplite.fp.sequence
 import com.sksamuel.hoplite.fp.valid
+import java.io.File
+import java.io.FileInputStream
 import java.io.InputStream
 import java.nio.file.Files
 import java.nio.file.Path
 
-sealed class FileSource {
+abstract class FileSource {
```
Comment (sksamuel) [inline hoplite-core/src/main/kotlin/com/sksamuel/hoplite/FileSource.kt]: Maybe we should rename FileSource to ConfigSource since it's not always files.

Then FileIoSource can just be FileSource.

File: hoplite-core/src/main/kotlin/com/sksamuel/hoplite/FileSource.kt [hunk 2]
```diff
@@ -47,5 +57,15 @@ sealed class FileSource {
       }.sequence()
         .mapInvalid { ConfigFailure.MultipleFailures(it) }
     }
+
+    fun fromFiles(files: List<File>): ConfigResult<List<FileSource>> {
+      return files.map { file ->
+        Try { FileInputStream(file) }.fold(
```
Comment (sksamuel) [inline hoplite-core/src/main/kotlin/com/sksamuel/hoplite/FileSource.kt]: Why does this try to load them first rather than error later ?

**Comment by sksamuel** [comment]
Thanks for the PR. comments added.

File: hoplite-core/src/main/kotlin/com/sksamuel/hoplite/FileSource.kt (hunk 1 above)
Comment (ttorjan) [reply hoplite-core/src/main/kotlin/com/sksamuel/hoplite/FileSource.kt]: Sounds good to me. Just tried to limit my changes as much as possible. :)

File: hoplite-core/src/main/kotlin/com/sksamuel/hoplite/FileSource.kt (hunk 2 above)
Comment (ttorjan) [reply hoplite-core/src/main/kotlin/com/sksamuel/hoplite/FileSource.kt]: I'm not quite sure what you mean. I tried to mirror the construction for fromPaths, but didn't really analyse exactly what was done there, so some things might not be appropriate. I re-wrote it from scratch given my understanding of what needs to be done, let me know if it looks better.

**Comment by sksamuel** [comment]
Excellent thanks
