### PR TITLE
Optionally make using an unresolved substitution value not an error a…

### LINKED ISSUE #296: Optionally make using an unresolved substitution value not an error again
Before [Hoplite 2](https://github.com/sksamuel/hoplite/blob/master/changelog.md#breaking-changes), it was not necessarily an error if unset environment variables were being referred to in the configuration. This was convenient, because if (e.g. for testing) only a subset of a (big) configuration was actually used, only the environment variables used by the code path were required to be set. Now, *all* variables need to be set, regardless of whether the respective configuration item is actually accessed at runtime or not.

Can we get an option to revert to the old behavior and allow unresolved variables, accepting late failure at runtime?

### LINKED ISSUE #298: Exception message should say "*Un*resolved substitution ..."
In here

https://github.com/sksamuel/hoplite/blob/142159606bb2146bc1244ecf7fec87f6e7e616f0/hoplite-core/src/main/kotlin/com/sksamuel/hoplite/ConfigFailure.kt#L99

I believe it should say "*Un*resolved substitution ..."

I'd be fine with filing a PR, but first wanted to double-check that you agree.

### PR DESCRIPTION
**Pull request by sksamuel**
Fixes #296 
Fixes #298

### CODE REVIEW

File: hoplite-core/src/main/kotlin/com/sksamuel/hoplite/ConfigFailure.kt [hunk 1]
```diff
@@ -96,7 +96,7 @@ sealed interface ConfigFailure {
 
   data class UnresolvedSubstitution(val value: String, val node: Node) : ConfigFailure {
     override fun description(): String {
-      return "Resolved substitution $value at ${node.pos.loc()}"
+      return "Unresolved substitution $value at ${node.pos.loc()}"
```
Comment (sschuberth) [inline hoplite-core/src/main/kotlin/com/sksamuel/hoplite/ConfigFailure.kt:99]: I guess this change should also update the test at https://github.com/sksamuel/hoplite/blob/e33c55aeaab773e290f701247a116e34f5912d70/hoplite-yaml/src/test/kotlin/com/sksamuel/hoplite/yaml/EnvVarPreprocessorTest.kt#L58, or?

Comment (sksamuel) [reply hoplite-core/src/main/kotlin/com/sksamuel/hoplite/ConfigFailure.kt:99]: Yep thanks.
